package tgis.fclts.service;

import java.util.HashMap;
import java.util.List;

import egovframework.rte.psl.dataaccess.mapper.Mapper;
import egovframework.rte.psl.dataaccess.util.EgovMap;

@Mapper("fcltsMngMapper")
public interface FcltsMngMapper {

	//시설물 등록
	int insertFcltsInfo_GT_A001_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A003_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A004_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A005_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A008_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A049_P (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A054_P (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A055_P (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A057_L (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A061_P (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A062_P (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A064_P (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A065_L (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A067_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A068_P (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A069_P (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A078_L (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A079_L (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A080_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A081_L (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A082_L (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A083_L (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A084_L (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A085_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A110_P (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A111_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_A090_P (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_B001_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C022_P (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C024_P (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C051_P (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C059_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C087_L (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C088_P (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C091_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C092_P (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C093_P (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C094_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C095_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C096_P (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C097_P (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C098_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C100_P (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C101_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C103_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C104_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C107_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C109_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C111_P (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C114_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C113_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C115_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C116_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C117_A (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C118_P (HashMap<String, Object> params) throws Exception;
	int insertFcltsInfo_GT_C123_L (HashMap<String, Object> params) throws Exception;

	EgovMap addr(HashMap<String, Object> params) throws Exception;

	EgovMap css(HashMap<String, Object> params) throws Exception;

	EgovMap sch(HashMap<String, Object> params) throws Exception;

	EgovMap police(HashMap<String, Object> params) throws Exception;

	EgovMap road(HashMap<String, Object> params) throws Exception;

	List<?> getIgtSignList(HashMap<String, Object> params) throws Exception;

	//시설물 조회
	EgovMap selectFcltsInfo_GT_A001_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A003_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A004_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A005_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A008_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A049_P(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A054_P(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A055_P(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A057_L(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A061_P(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A062_P(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A064_P(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A065_L(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A067_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A068_P(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A069_P(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A078_L(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A079_L(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A080_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A081_L(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A082_L(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A083_L(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A084_L(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A085_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A090_P(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A110_P(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_A111_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_B001_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C022_P(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C024_P(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C051_P(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C059_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C087_L(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C088_P(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C091_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C092_P(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C093_P(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C094_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C095_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C096_P(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C097_P(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C098_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C100_P(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C101_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C103_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C104_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C107_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C109_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C113_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C114_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C111_P(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C115_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C116_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C117_A(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C118_P(HashMap<String, Object> params) throws Exception;
	EgovMap selectFcltsInfo_GT_C123_L(HashMap<String, Object> params) throws Exception;

	//시설물 삭제
	int deleteFcltsInfo_GT_A001_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A003_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A004_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A005_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A008_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A049_P(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A054_P(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A055_P(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A057_L(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A061_P(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A062_P(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A064_P(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A065_L(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A067_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A068_P(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A069_P(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A078_L(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A079_L(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A080_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A081_L(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A082_L(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A083_L(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A084_L(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A085_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A090_P(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A110_P(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_A111_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_B001_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C022_P(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C024_P(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C051_P(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C059_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C087_L(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C088_P(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C091_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C092_P(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C093_P(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C094_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C095_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C096_P(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C097_P(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C098_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C100_P(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C101_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C103_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C104_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C107_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C109_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C111_P(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C113_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C114_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C115_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C116_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C117_A(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C118_P(HashMap<String, Object> params) throws Exception;
	int deleteFcltsInfo_GT_C123_L(HashMap<String, Object> params) throws Exception;

	//시설물 수정
	int updateFcltsInfo_GT_A001_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A003_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A004_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A005_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A008_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A049_P(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A054_P(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A055_P(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A057_L(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A061_P(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A062_P(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A064_P(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A065_L(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A067_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A068_P(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A069_P(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A078_L(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A079_L(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A080_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A081_L(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A082_L(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A083_L(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A084_L(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A085_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A090_P(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A110_P(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_A111_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_B001_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C022_P(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C024_P(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C051_P(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C059_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C087_L(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C088_P(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C091_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C092_P(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C093_P(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C094_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C095_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C096_P(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C097_P(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C098_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C100_P(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C101_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C104_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C103_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C107_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C109_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C111_P(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C114_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C113_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C115_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C116_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C117_A(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C118_P(HashMap<String, Object> params) throws Exception;
	int updateFcltsInfo_GT_C123_L(HashMap<String, Object> params) throws Exception;

	EgovMap selectReportFileInf(HashMap<String, Object> params) throws Exception;

	// 시설물 이미지 view
	EgovMap selectFacFileInf(HashMap<String, Object> params) throws Exception;

	//사진첨부
	String atchFileId() throws Exception;

	List<?> selectFileInfo(HashMap<String, Object> params) throws Exception;

    EgovMap selectFileInfoDetail(HashMap<String, Object> params) throws Exception;

	void insertFile(HashMap<String, Object> params) throws Exception;

    void insertFileMaster(String atchFileId) throws Exception;

    void insertFileDetail(HashMap<String, Object> params) throws Exception;

    void deleteFileMaster(HashMap<String, Object> params) throws Exception;

    void deleteFileDetail(HashMap<String, Object> params) throws Exception;

    void deleteFileInfo(HashMap<String, Object> params) throws Exception;

    //이력조회리스트
    List<?> selectWorkList_GT_A001_A(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A003_A(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A004_A(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A005_A(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A008_A(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A049_P(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A054_P(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A055_P(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A057_L(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A061_P(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A062_P(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A064_P(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A065_L(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A067_A(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A068_P(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A069_P(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A078_L(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A079_L(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A080_A(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A081_L(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A082_L(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A083_L(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A084_L(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A085_A(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A090_P(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A110_P(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_A111_A(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C022_P(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C024_P(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C051_P(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C059_A(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C087_L(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C088_P(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C091_A(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C092_P(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C093_P(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C094_A(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C095_A(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C096_P(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C097_P(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C098_A(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C100_P(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C101_A(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C103_A(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C104_A(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C107_A(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C109_A(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C111_P(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C114_A(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C115_A(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C117_A(HashMap<String, Object> params) throws Exception;
    List<?> selectWorkList_GT_C118_P(HashMap<String, Object> params) throws Exception;

    //이력등록
    int insertWorkList_GT_A001_A(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A003_A(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A004_A(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A005_A(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A008_A(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A049_P(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A054_P(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A055_P(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A057_L(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A061_P(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A062_P(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A064_P(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A065_L(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A067_A(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A068_P(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A069_P(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A078_L(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A079_L(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A080_A(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A081_L(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A082_L(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A083_L(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A084_L(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A085_A(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A090_P(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A110_P(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_A111_A(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C022_P(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C024_P(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C051_P(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C059_A(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C087_L(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C088_P(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C091_A(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C092_P(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C093_P(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C094_A(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C095_A(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C096_P(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C097_P(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C098_A(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C100_P(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C101_A(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C103_A(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C104_A(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C107_A(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C109_A(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C111_P(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C114_A(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C115_A(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C117_A(HashMap<String, Object> params) throws Exception;
    int insertWorkList_GT_C118_P(HashMap<String, Object> params) throws Exception;

    //이력상세보기
    EgovMap selectInfo_GT_A001_A(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A003_A(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A004_A(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A005_A(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A008_A(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A049_P(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A054_P(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A055_P(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A057_L(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A061_P(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A062_P(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A064_P(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A065_L(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A067_A(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A068_P(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A069_P(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A078_L(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A079_L(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A080_A(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A081_L(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A082_L(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A083_L(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A084_L(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A085_A(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A090_P(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A110_P(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_A111_A(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C022_P(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C024_P(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C051_P(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C059_A(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C087_L(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C088_P(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C091_A(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C092_P(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C093_P(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C094_A(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C095_A(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C096_P(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C097_P(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C098_A(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C100_P(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C101_A(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C103_A(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C104_A(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C107_A(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C109_A(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C111_P(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C114_A(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C115_A(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C117_A(HashMap<String, Object> params) throws Exception;
    EgovMap selectInfo_GT_C118_P(HashMap<String, Object> params) throws Exception;

    //이력수정
    int updateWorkList_GT_A001_A(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A003_A(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A004_A(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A005_A(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A008_A(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A049_P(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A054_P(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A055_P(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A057_L(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A061_P(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A062_P(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A064_P(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A065_L(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A067_A(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A068_P(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A069_P(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A078_L(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A079_L(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A080_A(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A081_L(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A082_L(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A083_L(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A084_L(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A085_A(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A090_P(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A110_P(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_A111_A(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C022_P(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C024_P(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C051_P(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C059_A(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C087_L(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C088_P(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C091_A(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C092_P(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C093_P(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C094_A(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C095_A(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C096_P(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C097_P(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C098_A(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C100_P(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C101_A(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C103_A(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C104_A(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C107_A(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C109_A(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C111_P(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C114_A(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C115_A(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C117_A(HashMap<String, Object> params) throws Exception;
    int updateWorkList_GT_C118_P(HashMap<String, Object> params) throws Exception;

    //이력삭제
    int deleteWorkList_GT_A001_A(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A003_A(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A004_A(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A005_A(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A008_A(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A049_P(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A054_P(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A055_P(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A057_L(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A061_P(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A062_P(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A064_P(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A065_L(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A067_A(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A068_P(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A069_P(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A078_L(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A079_L(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A080_A(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A081_L(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A082_L(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A083_L(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A084_L(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A085_A(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A090_P(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A110_P(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_A111_A(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C022_P(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C024_P(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C051_P(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C059_A(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C087_L(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C088_P(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C091_A(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C092_P(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C093_P(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C094_A(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C095_A(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C096_P(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C097_P(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C098_A(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C100_P(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C101_A(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C103_A(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C104_A(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C107_A(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C109_A(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C111_P(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C114_A(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C115_A(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C117_A(HashMap<String, Object> params) throws Exception;
    int deleteWorkList_GT_C118_P(HashMap<String, Object> params) throws Exception;

}
